# Generated by Django 2.0.2 on 2018-11-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-created'], 'verbose_name': 'Catálogo de producto', 'verbose_name_plural': 'Catálogo de productos'},
        ),
    ]
