# Generated by Django 2.0.2 on 2018-11-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181119_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
