# Generated by Django 2.0.2 on 2019-06-15 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190614_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='datos_pay',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Datos PayPal'),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='direccion',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_carrito', to='catalog.Design'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_comentarios', to='catalog.Design'),
        ),
    ]
