# Generated by Django 2.0.2 on 2019-06-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190615_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='catalog')),
            ],
        ),
        migrations.RemoveField(
            model_name='design',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='design',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='design',
            name='image',
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_carrito', to='catalog.Design'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_comentarios', to='catalog.Design'),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='imagenesproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_imagenes', to='catalog.Design'),
        ),
    ]
